Fix: Change filter parameter for api find Station by taxCode.
pagopa/selfcare-ms-party-registry-proxy pull request #112
Opened 2023-09-26 16:55 UTC by flaminiaScarciofolo

**List of Changes**

Change filter parameter for api find Station by taxCode.

2023-09-26 16:57 UTC, empassaro submitted a review, later dismissed

2023-09-26 17:54 UTC, manuraf requested changes
PR title is too general, try to write something more meaningful. PR description should not be empty, you should follow the repository template.

2023-09-26 17:54 UTC, manuraf commented on core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/StationServiceImpl.java
> +        taxId = "ANAC_" + taxId;
you could introduce a constant class for string "ANAC_", for ex. ANAC_PREFIX = "ANAC_"....it's better avoiding to use hardcoded string

2023-09-27 07:43 UTC, manuraf approved these changes

2023-09-27 07:45 UTC, merged